apiVersion: v1
kind: Service
metadata:
  name: accounts-db
  namespace: fsi
  labels:
    app: accounts-db
    tier: db
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: accounts-db
    tier: db
---
apiVersion: v1
kind: Service
metadata:
  name: contacts
  namespace: fsi
spec:
  type: ClusterIP
  selector:
    app: contacts
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: fsi
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
  namespace: fsi
spec:
  type: ClusterIP
  selector:
    app: userservice
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: loadgenerator
  namespace: fsi
spec:
  type: ClusterIP
  selector:
    app: loadgenerator
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: balancereader
  namespace: fsi
spec:
  type: ClusterIP
  selector:
    app: balancereader
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ledger-db
  namespace: fsi
spec:
  type: ClusterIP
  selector:
    app: ledger-db
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: ledgerwriter
  namespace: fsi
spec:
  type: ClusterIP
  selector:
    app: ledgerwriter
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: transactionhistory
  namespace: fsi
spec:
  type: ClusterIP
  selector:
    app: transactionhistory
  ports:
  - name: http
    port: 8080
    targetPort: 8080
