apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cli
spec:
  selector:
    matchLabels:
      app: redis-cli
  template:
    metadata:
      labels:
        app: redis-cli
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: main
        image: redis:latest