apiVersion: v1
kind: Service
metadata:
  name: balancereader
  namespace: fsi
spec:
  type: ClusterIP
  selector:
    app: balancereader
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ledger-db
  namespace: fsi
spec:
  type: ClusterIP
  selector:
    app: ledger-db
  ports:
  - name: tcp
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: ledgerwriter
  namespace: fsi
spec:
  type: ClusterIP
  selector:
    app: ledgerwriter
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: transactionhistory
  namespace: fsi
spec:
  type: ClusterIP
  selector:
    app: transactionhistory
  ports:
  - name: http
    port: 8080
    targetPort: 8080